#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-3.0+

START=45

start() {
	swconfig dev eth0 set phy 30
	swconfig dev eth0 set reg 16
	if [ "`swconfig dev eth0 get val`" = "7967" ]; then
		swconfig dev eth0 set val 31
	fi
}

stop() {
	swconfig dev eth0 set phy 30
	swconfig dev eth0 set reg 16
	if [ "`swconfig dev eth0 get val`" = "31" ]; then
		swconfig dev eth0 set val 7967
	fi
}
